### ISSUE TITLE
未来会有机会适配py3.8+吗？

### ISSUE THREAD

**Issue by ElainaFanBoy** [CofinCup/nonebot-plugin-todo-nlp#1]
未来会有机会适配py3.8+吗？

**Comment by CofinCup** [comment]
> 未来会有机会适配py3.8+吗？

我今天试了下，似乎跟3.8+没有冲突，我待会改一下toml和lock文件重新上传一份，有遇到什么特性上的问题吗？

**Comment by ElainaFanBoy** [comment]
我之前试了一下，pip或者nb plugin都无法安装，提示需要py3.9+，然后就没继续试了qwq

**Comment by CofinCup** [comment]
> 我之前试了一下，pip或者nb plugin都无法安装，提示需要py3.9+，然后就没继续试了qwq

0.1.5版本现在适配了3.8（而且修改了一点弱智错误，如果发现bug请继续issue，阿里嘎多
