### ISSUE TITLE
是否能给白名单

### ISSUE THREAD

**Issue by assassinliujie** [CofinCup/nonebot-plugin-todo-nlp#12]
现在只有管理能编辑，能否变成所有人可以编辑或者白名单的人可以编辑

**Comment by CofinCup** [comment]
这可能跟我的设计初衷有些差异，如果需要这个功能你可以去把本地插件的[这里](https://github.com/CofinCup/nonebot-plugin-todo-nlp/blob/1ad285891dbddda46bb69aa3b79377e69dd307ca/nonebot_plugin_todo_nlp/todo_manage.py#L17C2-L17C2)的几个permission=.*删掉
> （而且因为好久不写nb代码了已经忘了permission怎么修改了，欢迎pr）
