### ISSUE TITLE
云服务器用不了好像

### ISSUE THREAD

**Issue by krasus1995** [CofinCup/nonebot-plugin-todo-nlp#4]
2g内存，我云服务器一用插件就爆炸了。。。

**Comment by krasus1995** [comment]
![image](https://user-images.githubusercontent.com/97447697/191476697-dde58578-b859-4549-9e23-397f2b4c33ef.png)

**Comment by CofinCup** [comment]
抱歉，之前回复似乎没发成功（然后一直忘了），和群友讨论了这个问题，应该是因为图片渲染用了chromium内核，比较吃内存（而且jionlp可能也吃内存）

**Comment by CofinCup** [comment]
我最近也遇到相关的问题（跑人工智能的时候另一个端口上开了code server占了2g, 结果人工智能直接killed），只能说服务器2g内存实在还是太过孱弱，浏览器内核（建议火速利用钞能力升级服务器内存！应该会有不少插件用htmlrender插件来渲染，而chromium内核就是htmlrender所需要的）

**Comment by krasus1995** [comment]
艹，没钱只能停机器了，用电脑挂
