### ISSUE TITLE
内存占用是否有点大

### ISSUE THREAD

**Issue by newcovid** [CofinCup/nonebot-plugin-todo-nlp#6]
加了插件后过一会占用增加1G多,是冲突还是?

**Comment by CofinCup** [comment]
> 加了插件后过一会占用增加1G多,是冲突还是?

跟实现有关，算是chromium内核的问题
图片渲染本质上用的是playwright开了个浏览器->开一个预编辑的html文件->图片保存进来
问题就在于chromium内核占很大的内存，前面甚至有人因为是2g机子，运行了其他内容后内存炸了被强制kill（我的经验上一般chromium稳定占用在1g上下）
