### ISSUE TITLE
ubuntu上卡死

### ISSUE THREAD

**Issue by Mashiroyes** [CofinCup/nonebot-plugin-todo-nlp#9]
windows上可以正常使用，但是ubuntu上使用时加载这个add_todu_handle函数直接卡死
![X2~NR9S}X XTFF( 8KH}Y_U](https://user-images.githubusercontent.com/59597481/222875078-461258fb-a45c-4b75-9130-cc15f85f84ef.png)

**Comment by CofinCup** [comment]
服务器内存多大？

**Comment by Mashiroyes** [comment]
2GB

**Comment by Mashiroyes** [comment]
> 服务器内存多大？

2GB

**Comment by CofinCup** [comment]
> > 服务器内存多大？
> 
> 2GB

喜报 应该是你内存炸了
用于渲染的chromium内核就能吃掉1g+，前面有issue也是小服务器内存炸了（建议内存4g以上用）

**Comment by Mashiroyes** [comment]
> > > 服务器内存多大？
> > 
> > 
> > 2GB
> 
> 喜报 应该是你内存炸了 用于渲染的chromium内核就能吃掉1g+，前面有issue也是小服务器内存炸了（建议内存4g以上用）

www，行吧，其实猜到是内存炸了233，想看看有没有什么别的解决办法，渲染就要1G，看来是没办法了。
